// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs0iqXRXovyG43iPkx2ElLgdwzzgDNlpk',
    appId: '1:456728615081:web:b032293755b50347ecb1b8',
    messagingSenderId: '456728615081',
    projectId: 'josmatech',
    authDomain: 'josmatech.firebaseapp.com',
    storageBucket: 'josmatech.appspot.com',
    measurementId: 'G-CPTM93QVDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOCy9LHexM3Rn4xm1eO2qaggJV7iOghyY',
    appId: '1:456728615081:android:1d0e236ff4b15ab3ecb1b8',
    messagingSenderId: '456728615081',
    projectId: 'josmatech',
    storageBucket: 'josmatech.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1INvD5VHHpEHP1TahvPUV5baWzncvLQ4',
    appId: '1:456728615081:ios:4c6cf8a660844c57ecb1b8',
    messagingSenderId: '456728615081',
    projectId: 'josmatech',
    storageBucket: 'josmatech.appspot.com',
    iosBundleId: 'com.example.josmaTech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1INvD5VHHpEHP1TahvPUV5baWzncvLQ4',
    appId: '1:456728615081:ios:4c6cf8a660844c57ecb1b8',
    messagingSenderId: '456728615081',
    projectId: 'josmatech',
    storageBucket: 'josmatech.appspot.com',
    iosBundleId: 'com.example.josmaTech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs0iqXRXovyG43iPkx2ElLgdwzzgDNlpk',
    appId: '1:456728615081:web:8c9eb788332736feecb1b8',
    messagingSenderId: '456728615081',
    projectId: 'josmatech',
    authDomain: 'josmatech.firebaseapp.com',
    storageBucket: 'josmatech.appspot.com',
    measurementId: 'G-93RVVG3N57',
  );

}